<?php

/**
 * @file
 */

/**
 * Implements hook_form_form_id_form_alter().
 */
function check_dns_form_user_register_form_alter(&$form, &$form_state, $form_id) {
  $form['#validate'][] = 'check_dns_user_register_validate';
}

/**
 * Custom validation function.
 *
 * Checks if the domain in the email address is on a list of allowed domains.
 */
function check_dns_user_register_validate(&$form, &$form_state) {
  // Ignore validation if mail already has an error.
  $errors = form_get_errors();
  if (!empty($errors['mail'])) {
    return;
  }
  $default_message = t('Your email domain is not recognised. Please enter a valid email id.');
  $mail = explode('@', $form_state['values']['mail']);

  $result = dns_get_record(end($mail), DNS_ALL);

  if (empty($result)) {
    form_set_error('account', $default_message);
  }
  else {
    return;
  }

}
